import type { RolePermissions } from "@grwfit/shared-types";

export const PERMISSIONS: RolePermissions = {
  owner: {
    dashboard: ["view", "create", "edit", "delete"],
    members: ["view", "create", "edit", "delete"],
    checkins: ["view", "create", "edit", "delete"],
    payments: ["view", "create", "edit", "delete"],
    plans: ["view", "create", "edit", "delete"],
    workout_diet: ["view", "create", "edit", "delete"],
    leads: ["view", "create", "edit", "delete"],
    reports: ["view", "create", "edit", "delete"],
    staff_mgmt: ["view", "create", "edit", "delete"],
    website_cms: ["view", "create", "edit", "delete"],
    billing: ["view", "create", "edit", "delete"],
    commission: ["view", "create", "edit", "delete"],
  },
  manager: {
    dashboard: ["view"],
    members: ["view", "create", "edit"],
    checkins: ["view", "create"],
    payments: ["view", "create"],
    plans: ["view", "create", "edit"],
    workout_diet: ["view", "create", "edit"],
    leads: ["view", "create", "edit"],
    reports: ["view"],
    staff_mgmt: [],
    website_cms: ["view", "edit"],
    billing: [],
    commission: ["view"],
  },
  trainer: {
    dashboard: ["view"],
    members: ["view"],
    checkins: ["view"],
    payments: [],
    plans: ["view", "create", "edit"],
    workout_diet: ["view", "create", "edit"],
    leads: [],
    reports: [],
    staff_mgmt: [],
    website_cms: [],
    billing: [],
    commission: ["view"],
  },
  reception: {
    dashboard: ["view"],
    members: ["view", "create"],
    checkins: ["view", "create"],
    payments: ["view", "create"],
    plans: ["view"],
    workout_diet: [],
    leads: ["view", "create", "edit"],
    reports: [],
    staff_mgmt: [],
    website_cms: [],
    billing: [],
    commission: [],
  },
};
